// Seed rules: global (common merchants) + per-industry. All rows have
// user_id NULL. Confidence >= 0.9 auto-applies (status 'auto', still pinged);
// lower confidence rows are passed to Claude as hints.

type SeedRule = {
  pattern: string;
  category: string;
  businessPersonal: "business" | "personal";
  confidence: number;
};

export const GLOBAL_RULES: SeedRule[] = [
  // Software & services common to all creative businesses
  { pattern: "adobe", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "canva", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "dropbox", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "google workspace", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "google storage", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.85 },
  { pattern: "notion", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "slack", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "zoom.us", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "calendly", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  { pattern: "quickbooks", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
  { pattern: "intuit", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.85 },
  { pattern: "mailchimp", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.9 },
  { pattern: "squarespace", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.9 },
  { pattern: "wix.com", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.9 },
  { pattern: "godaddy", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.9 },
  { pattern: "namecheap", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.9 },
  { pattern: "meta ads", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.95 },
  { pattern: "facebook ads", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.95 },
  { pattern: "google ads", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.95 },
  { pattern: "linkedin", category: "Advertising & marketing", businessPersonal: "business", confidence: 0.7 },
  { pattern: "upwork", category: "Contract labor", businessPersonal: "business", confidence: 0.9 },
  { pattern: "fiverr", category: "Contract labor", businessPersonal: "business", confidence: 0.9 },
  { pattern: "stripe", category: "Bank & payment fees", businessPersonal: "business", confidence: 0.7 },
  { pattern: "paypal", category: "Other", businessPersonal: "business", confidence: 0.4 },
  { pattern: "wework", category: "Rent & studio space", businessPersonal: "business", confidence: 0.9 },
  { pattern: "usps", category: "Office supplies", businessPersonal: "business", confidence: 0.7 },
  { pattern: "fedex", category: "Office supplies", businessPersonal: "business", confidence: 0.7 },
  { pattern: "ups store", category: "Office supplies", businessPersonal: "business", confidence: 0.7 },
  { pattern: "staples", category: "Office supplies", businessPersonal: "business", confidence: 0.8 },
  { pattern: "office depot", category: "Office supplies", businessPersonal: "business", confidence: 0.8 },
  { pattern: "uber", category: "Travel", businessPersonal: "business", confidence: 0.5 },
  { pattern: "lyft", category: "Travel", businessPersonal: "business", confidence: 0.5 },
  { pattern: "delta air", category: "Travel", businessPersonal: "business", confidence: 0.6 },
  { pattern: "united airlines", category: "Travel", businessPersonal: "business", confidence: 0.6 },
  { pattern: "american airlines", category: "Travel", businessPersonal: "business", confidence: 0.6 },
  { pattern: "southwest", category: "Travel", businessPersonal: "business", confidence: 0.6 },
  { pattern: "airbnb", category: "Travel", businessPersonal: "business", confidence: 0.5 },
  { pattern: "marriott", category: "Travel", businessPersonal: "business", confidence: 0.6 },
  { pattern: "hilton", category: "Travel", businessPersonal: "business", confidence: 0.6 },
  { pattern: "shell oil", category: "Vehicle & mileage", businessPersonal: "business", confidence: 0.5 },
  { pattern: "chevron", category: "Vehicle & mileage", businessPersonal: "business", confidence: 0.5 },
  { pattern: "exxon", category: "Vehicle & mileage", businessPersonal: "business", confidence: 0.5 },
  // Clearly personal defaults
  { pattern: "netflix", category: "Personal", businessPersonal: "personal", confidence: 0.95 },
  { pattern: "spotify", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "hulu", category: "Personal", businessPersonal: "personal", confidence: 0.95 },
  { pattern: "disney plus", category: "Personal", businessPersonal: "personal", confidence: 0.95 },
  { pattern: "doordash", category: "Personal", businessPersonal: "personal", confidence: 0.8 },
  { pattern: "grubhub", category: "Personal", businessPersonal: "personal", confidence: 0.8 },
  { pattern: "instacart", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "whole foods", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "trader joe", category: "Personal", businessPersonal: "personal", confidence: 0.9 },
  { pattern: "safeway", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "kroger", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "cvs", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "walgreens", category: "Personal", businessPersonal: "personal", confidence: 0.85 },
  { pattern: "planet fitness", category: "Personal", businessPersonal: "personal", confidence: 0.9 },
  { pattern: "amazon", category: "Other", businessPersonal: "business", confidence: 0.3 },
  { pattern: "target", category: "Personal", businessPersonal: "personal", confidence: 0.6 },
  { pattern: "walmart", category: "Personal", businessPersonal: "personal", confidence: 0.6 },
  { pattern: "costco", category: "Personal", businessPersonal: "personal", confidence: 0.5 },
  { pattern: "starbucks", category: "Personal", businessPersonal: "personal", confidence: 0.6 },
  { pattern: "mcdonald", category: "Personal", businessPersonal: "personal", confidence: 0.8 },
  { pattern: "chipotle", category: "Personal", businessPersonal: "personal", confidence: 0.7 },
];

export const INDUSTRY_RULES: Record<string, SeedRule[]> = {
  videography: [
    { pattern: "b&h photo", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "bhphoto", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "adorama", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "sweetwater", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
    { pattern: "lensrentals", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "borrowlenses", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "sharegrid", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "kittsplit", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "red digital", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "blackmagic", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "dji", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
    { pattern: "gopro", category: "Equipment", businessPersonal: "business", confidence: 0.85 },
    { pattern: "sandisk", category: "Equipment", businessPersonal: "business", confidence: 0.85 },
    { pattern: "frame.io", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "vimeo", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "artgrid", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "artlist", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "epidemic sound", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "musicbed", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "storyblocks", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "envato", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "maxon", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "davinci resolve", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
  ],
  photography: [
    { pattern: "b&h photo", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "bhphoto", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "adorama", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "mpb.com", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "keh camera", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "lensrentals", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "borrowlenses", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "profoto", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "godox", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
    { pattern: "peak design", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
    { pattern: "sandisk", category: "Equipment", businessPersonal: "business", confidence: 0.85 },
    { pattern: "pixieset", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "pic-time", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "shootproof", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "smugmug", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "zenfolio", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "honeybook", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "capture one", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "narrative.so", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "printique", category: "Office supplies", businessPersonal: "business", confidence: 0.9 },
    { pattern: "whcc", category: "Office supplies", businessPersonal: "business", confidence: 0.9 },
    { pattern: "bay photo", category: "Office supplies", businessPersonal: "business", confidence: 0.9 },
  ],
  podcasting: [
    { pattern: "riverside.fm", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "descript", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "buzzsprout", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "transistor.fm", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "libsyn", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "podbean", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "captivate.fm", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "squadcast", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "auphonic", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "rev.com", category: "Contract labor", businessPersonal: "business", confidence: 0.9 },
    { pattern: "shure", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
    { pattern: "rode", category: "Equipment", businessPersonal: "business", confidence: 0.85 },
    { pattern: "focusrite", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
    { pattern: "zoom corp", category: "Equipment", businessPersonal: "business", confidence: 0.8 },
    { pattern: "sweetwater", category: "Equipment", businessPersonal: "business", confidence: 0.9 },
  ],
  design: [
    { pattern: "figma", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "sketch", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.85 },
    { pattern: "framer", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "webflow", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "dribbble", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "behance", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "fontshare", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "myfonts", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "creative market", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "shutterstock", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "wacom", category: "Equipment", businessPersonal: "business", confidence: 0.95 },
    { pattern: "pantone", category: "Office supplies", businessPersonal: "business", confidence: 0.9 },
  ],
  marketing_consulting: [
    { pattern: "hubspot", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "semrush", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "ahrefs", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "hootsuite", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "buffer", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "sprout social", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "later.com", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "klaviyo", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "convertkit", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "beehiiv", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.95 },
    { pattern: "typeform", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "airtable", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "anthropic", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
    { pattern: "openai", category: "Software & subscriptions", businessPersonal: "business", confidence: 0.9 },
  ],
};
