import Link from "next/link";

export const metadata = { title: "Terms of Service — Listero" };

const UPDATED = "July 3, 2026";

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="mb-2 mt-8 text-xl font-bold">{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="mb-3 text-sm leading-relaxed text-ink-soft">{children}</p>;
}

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12">
      <h1 className="mb-1 text-3xl font-bold">Terms of Service</h1>
      <p className="mb-8 text-sm text-ink-soft">Last updated: {UPDATED}</p>

      <P>
        These terms are an agreement between you and Listero, operated by
        Viola Visuals LLC (&quot;Listero&quot;, &quot;we&quot;, &quot;us&quot;). By
        creating an account or using Listero you agree to them. If you
        don&apos;t agree, don&apos;t use the service.
      </P>

      <H2>1. What Listero is — and is not</H2>
      <P>
        Listero is a bookkeeping assistant: it imports your business
        transactions, proposes categorizations with AI-generated reasoning,
        and records the decisions <em>you</em> make.{" "}
        <strong>
          Listero is not an accounting firm, tax advisor, financial advisor,
          or law firm, and nothing it produces — categories, deductibility
          hints, tax explanations, savings estimates, or any other output —
          is tax, financial, legal, or investment advice.
        </strong>{" "}
        All such content is educational and general in nature. You are solely
        responsible for your books, your tax filings, and the decisions you
        make; consult a qualified professional for advice about your specific
        situation.
      </P>

      <H2>2. AI-generated content can be wrong</H2>
      <P>
        Listero&apos;s proposals are generated by automated systems, including
        large language models. They may be inaccurate, incomplete, or
        inapplicable to your situation, and identical inputs will not always
        produce identical outputs. The product is designed so that{" "}
        <strong>you confirm every categorization</strong> — by tapping a
        button, replying, or setting a rule. You agree that you, not Listero,
        are the final decision-maker for how transactions are classified, and
        that you will review categorizations before relying on them for any
        tax or financial purpose.
      </P>

      <H2>3. Your account and data</H2>
      <P>
        You must provide accurate information and keep your login secure. You
        must only connect financial accounts you are authorized to access.
        Your data remains yours: you can export everything at any time and
        request deletion as described in our{" "}
        <Link href="/privacy" className="text-coral underline">
          Privacy Policy
        </Link>
        . Bank connections are read-only; Listero cannot initiate payments or
        transfers.
      </P>

      <H2>4. Acceptable use</H2>
      <P>
        Don&apos;t misuse the service: no unauthorized access, no reverse
        engineering, no using Listero for unlawful activity, and no attempting
        to access another user&apos;s data. We may suspend accounts that do.
      </P>

      <H2>5. Third-party services</H2>
      <P>
        Listero depends on third parties (Plaid, Slack, Anthropic, and our
        hosting providers). Their availability and terms are outside our
        control, and your use of Plaid is also subject to Plaid&apos;s
        end-user terms and privacy policy. Bank data can arrive delayed,
        incomplete, or occasionally wrong at the source.
      </P>

      <H2>6. Beta service; availability</H2>
      <P>
        Listero is currently offered as a beta, free of charge. The service is
        provided <strong>&quot;as is&quot; and &quot;as available&quot;,
        without warranties of any kind</strong>, express or implied, including
        fitness for a particular purpose and accuracy. We may change, suspend,
        or discontinue features at any time. If we ever introduce paid plans,
        we will give you clear notice first.
      </P>

      <H2>7. Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law: Listero and its operator will
        not be liable for any indirect, incidental, special, consequential, or
        punitive damages — including lost profits, tax penalties, interest,
        or costs arising from categorizations, estimates, or other outputs —
        and our total aggregate liability for any claim relating to the
        service is limited to the greater of the amount you paid us in the
        twelve months before the claim or fifty dollars ($50). Some
        jurisdictions don&apos;t allow certain limitations, so parts of this
        section may not apply to you.
      </P>

      <H2>8. Indemnity</H2>
      <P>
        You agree to indemnify us against claims arising from your misuse of
        the service or violation of these terms.
      </P>

      <H2>9. Disputes</H2>
      <P>
        These terms are governed by the laws of the State of Florida, USA.
        Before filing any claim, you agree to contact us and give us 30 days
        to work it out informally. Any dispute that can&apos;t be resolved
        informally will be brought in the state or federal courts located in
        Pinellas County, Florida, and each party waives any right to a jury
        trial or to participate in a class action, to the extent permitted by
        law.
      </P>

      <H2>10. Changes to these terms</H2>
      <P>
        If we make material changes, we&apos;ll notify you by email or in-app
        before they take effect. Continuing to use Listero after that means
        you accept the updated terms.
      </P>

      <H2>Contact</H2>
      <P>
        <a href="mailto:grant@orangegrovesocial.com" className="text-coral underline">
          grant@orangegrovesocial.com
        </a>
      </P>

      <p className="mt-10 text-sm">
        <Link href="/" className="text-coral underline">← Back to Listero</Link>
      </p>
    </main>
  );
}
